CREATE USER synapse WITH PASSWORD 'synapse_dev_password_2026';
CREATE DATABASE synapse OWNER synapse ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE synapse TO synapse;
