"""initial schema

Revision ID: 28a444422e2c
Revises: 
Create Date: 2026-04-24 22:55:12.087808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '28a444422e2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('government_id_encrypted', sa.Text(), nullable=False),
    sa.Column('government_id_hmac', sa.String(length=64), nullable=False),
    sa.Column('id_country_code', sa.String(length=3), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('phone_country_code', sa.String(length=5), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_age_restricted', sa.Boolean(), nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('student', 'tutor', 'parent', 'admin')", name='ck_accounts_account_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'account_type'),
    sa.UniqueConstraint('government_id_hmac', 'account_type')
    )
    op.create_index('idx_accounts_active', 'accounts', ['id'], unique=False, postgresql_where='is_active = TRUE')
    op.create_index('idx_accounts_age_restricted', 'accounts', ['id'], unique=False, postgresql_where='is_age_restricted = TRUE')
    op.create_index('idx_accounts_email_type', 'accounts', ['email', 'account_type'], unique=False)
    op.create_index('idx_accounts_pending_deletion', 'accounts', ['id'], unique=False, postgresql_where='deletion_scheduled_for IS NOT NULL')
    op.create_table('countries',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('education_levels',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('sent', 'failed')", name='ck_email_logs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=True),
    sa.Column('target_entity_type', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_profiles',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_unread', 'notifications', ['account_id'], unique=False, postgresql_where='is_read = FALSE')
    op.create_table('parent_invite_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('parent_email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_profiles',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('parent_student_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'active')", name='ck_parent_student_links_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id')
    )
    op.create_table('parent_tutor_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'granted', 'denied')", name='ck_parent_tutor_permissions_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', 'tutor_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'code')
    )
    op.create_table('reviews',
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('admin_deletion_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating'),
    sa.CheckConstraint("is_deleted = FALSE OR admin_deletion_reason IS NOT NULL", name='ck_reviews_deletion_reason'),
    sa.ForeignKeyConstraint(['deleted_by_admin_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reviews_tutor_active', 'reviews', ['tutor_id'], unique=False, postgresql_where='is_deleted = FALSE')
    op.create_table('sessions',
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('location_region', sa.String(length=100), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('series_root_id', sa.Uuid(), nullable=True),
    sa.Column('max_group_size', sa.Integer(), nullable=True),
    sa.Column('jitsi_room_name', sa.String(length=100), nullable=True),
    sa.Column('individual_rate_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('group_rate_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_override', sa.String(length=3), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('online', 'physical', 'hybrid')", name='ck_sessions_mode'),
    sa.CheckConstraint("session_type IN ('booking_meeting', 'individual_class', 'group_class')", name='ck_sessions_type'),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'cancelled')", name='ck_sessions_status'),
    sa.CheckConstraint('duration_minutes IN (30, 45, 60, 90, 120)', name='ck_sessions_duration'),
    sa.ForeignKeyConstraint(['series_root_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_active', 'sessions', ['id'], unique=False, postgresql_where="status = 'active'")
    op.create_index('idx_sessions_series_root', 'sessions', ['series_root_id'], unique=False, postgresql_where='series_root_id IS NOT NULL')
    op.create_index('idx_sessions_start_time', 'sessions', ['start_time'], unique=False)
    op.create_index('idx_sessions_tutor', 'sessions', ['tutor_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('education_level_id', sa.Uuid(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_levels.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('subjects',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['subject_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name')
    )
    op.create_table('tutor_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('contact_account_id', sa.Uuid(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("contact_type IN ('student', 'parent')", name='ck_tutor_contacts_type'),
    sa.ForeignKeyConstraint(['contact_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id', 'contact_account_id')
    )
    op.create_table('tutor_ml_vectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('cancellation_rate_48h', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reschedule_rate_48h', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sessions_per_week_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_students_taught', sa.Integer(), nullable=False),
    sa.Column('total_sessions_completed', sa.Integer(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_table('tutor_sentiment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_table('tutor_working_hours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6'),
    sa.ForeignKeyConstraint(['tutor_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id', 'day_of_week')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('qr_scan', 'jitsi_webhook')", name='ck_attendance_method'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id')
    )
    op.create_table('chat_room_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('matrix_room_id', sa.String(length=255), nullable=False),
    sa.Column('room_type', sa.String(length=20), nullable=False),
    sa.Column('account_id_1', sa.Uuid(), nullable=True),
    sa.Column('account_id_2', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("room_type IN ('dm', 'broadcast')", name='ck_chat_room_type'),
    sa.ForeignKeyConstraint(['account_id_1'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['account_id_2'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id_1', 'account_id_2', name='uq_chat_dm_pair'),
    sa.UniqueConstraint('matrix_room_id')
    )
    op.create_table('cities',
    sa.Column('region_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrolments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'opted_out')", name='ck_enrolments_status'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id')
    )
    op.create_table('jitsi_rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_name')
    )
    op.create_table('occurrence_exceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('series_root_id', sa.Uuid(), nullable=False),
    sa.Column('original_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_root_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_root_id', 'original_start_time')
    )
    op.create_table('qr_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurrence_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('days_of_week', postgresql.JSONB(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("frequency IN ('weekly', 'biweekly', 'monthly')", name='ck_recurrence_frequency'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('review_authorships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id'),
    sa.UniqueConstraint('student_id', 'tutor_id')
    )
    op.create_table('review_duration_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('sessions_attended', sa.Integer(), nullable=False),
    sa.Column('approximate_duration_weeks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_table('session_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conflict_details', sa.JSON(), nullable=True),
    sa.Column('declined_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined')", name='ck_session_invites_status'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id')
    )
    op.create_table('student_subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('education_level_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_levels.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'education_level_id')
    )
    op.create_table('subject_level_availability',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('education_level_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'education_level_id')
    )
    op.create_table('tutor_subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('education_level_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['education_level_id'], ['education_levels.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id', 'subject_id', 'education_level_id')
    )
    op.create_table('tutor_profiles',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('mode_of_tuition', sa.String(length=20), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('individual_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('group_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_profile_complete', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor_profiles')
    op.drop_table('tutor_subjects')
    op.drop_table('subject_level_availability')
    op.drop_table('student_subjects')
    op.drop_table('session_invites')
    op.drop_table('review_duration_signals')
    op.drop_table('review_authorships')
    op.drop_table('recurrence_rules')
    op.drop_table('qr_tokens')
    op.drop_table('occurrence_exceptions')
    op.drop_table('jitsi_rooms')
    op.drop_table('enrolments')
    op.drop_table('cities')
    op.drop_table('chat_room_mappings')
    op.drop_table('attendance_records')
    op.drop_table('tutor_working_hours')
    op.drop_table('tutor_sentiment')
    op.drop_table('tutor_ml_vectors')
    op.drop_table('tutor_contacts')
    op.drop_table('subjects')
    op.drop_table('student_profiles')
    op.drop_index('idx_sessions_tutor', table_name='sessions')
    op.drop_index('idx_sessions_start_time', table_name='sessions')
    op.drop_index('idx_sessions_series_root', table_name='sessions', postgresql_where='series_root_id IS NOT NULL')
    op.drop_index('idx_sessions_active', table_name='sessions', postgresql_where="status = 'active'")
    op.drop_table('sessions')
    op.drop_index('idx_reviews_tutor_active', table_name='reviews', postgresql_where='is_deleted = FALSE')
    op.drop_table('reviews')
    op.drop_table('regions')
    op.drop_table('refresh_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('parent_tutor_permissions')
    op.drop_table('parent_student_links')
    op.drop_table('parent_profiles')
    op.drop_table('parent_invite_tokens')
    op.drop_index('idx_notifications_unread', table_name='notifications', postgresql_where='is_read = FALSE')
    op.drop_table('notifications')
    op.drop_table('email_verification_tokens')
    op.drop_table('admin_profiles')
    op.drop_table('admin_audit_log')
    op.drop_table('subject_categories')
    op.drop_table('email_logs')
    op.drop_table('education_levels')
    op.drop_table('countries')
    op.drop_index('idx_accounts_pending_deletion', table_name='accounts', postgresql_where='deletion_scheduled_for IS NOT NULL')
    op.drop_index('idx_accounts_email_type', table_name='accounts')
    op.drop_index('idx_accounts_age_restricted', table_name='accounts', postgresql_where='is_age_restricted = TRUE')
    op.drop_index('idx_accounts_active', table_name='accounts', postgresql_where='is_active = TRUE')
    op.drop_table('accounts')
    # ### end Alembic commands ###
