server_name: "localhost"
pid_file: /data/homeserver.pid

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false

database:
  name: psycopg2
  args:
    user: synapse
    password: CHANGE_ME_synapse_db_password
    database: synapse
    host: postgres
    port: 5432
    cp_min: 5
    cp_max: 10

log_config: "/data/log.config"

media_store_path: /data/media_store
uploads_path: /data/uploads

registration_shared_secret: "CHANGE_ME_generate_with_python_c_import_secrets_secrets_token_hex_32"
enable_registration: false
enable_registration_without_verification: false

report_stats: false

macaroon_secret_key: "CHANGE_ME_generate_with_python_c_import_secrets_secrets_token_hex_32"
form_secret: "CHANGE_ME_generate_with_python_c_import_secrets_secrets_token_hex_32"
signing_key_path: "/data/localhost.signing.key"

trusted_key_servers:
  - server_name: "matrix.org"

suppress_key_server_warning: true

enable_metrics: false

rc_message:
  per_second: 5
  burst_count: 15

rc_login:
  address:
    per_second: 1
    burst_count: 5
  account:
    per_second: 1
    burst_count: 5
