server_name: "localhost"
pid_file: /data/homeserver.pid

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false

database:
  name: psycopg2
  args:
    user: synapse
    password: synapse_dev_password_2026
    database: synapse
    host: postgres
    port: 5432
    cp_min: 5
    cp_max: 10

log_config: "/data/log.config"

media_store_path: /data/media_store
uploads_path: /data/uploads

registration_shared_secret: "5cd060c3850722467b999a6a4cbe4d83bab33c3cf4934fffaa6e4a7578372e66"
enable_registration: false
enable_registration_without_verification: false

report_stats: false

macaroon_secret_key: "01814fce01168da706bc0135fdbb5a5ff81bc1c451c6f59971f517276eb92be9"
form_secret: "cbf4954b5c7c00871b44b84ebebbf22cb2a725091299c942247b5a823a38b356"
signing_key_path: "/data/localhost.signing.key"

trusted_key_servers:
  - server_name: "matrix.org"

suppress_key_server_warning: true

enable_metrics: false

rc_message:
  per_second: 5
  burst_count: 15

rc_login:
  address:
    per_second: 1
    burst_count: 5
  account:
    per_second: 1
    burst_count: 5
